# Generated by Django 4.2.7 on 2025-11-03 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='📚', max_length=50, verbose_name='Иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('author', models.CharField(max_length=300, verbose_name='Автор')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=300, null=True, verbose_name='Издательство')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('edition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Издание')),
                ('circulation', models.IntegerField(blank=True, null=True, verbose_name='Тираж')),
                ('language', models.CharField(default='Русский', max_length=50, verbose_name='Язык')),
                ('binding', models.CharField(blank=True, max_length=100, null=True, verbose_name='Переплет')),
                ('format', models.CharField(blank=True, max_length=50, null=True, verbose_name='Формат')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Вес (г)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(verbose_name='Номер страницы')),
                ('original_image', models.ImageField(upload_to='books/pages/original/', verbose_name='Оригинал')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='books/pages/processed/', verbose_name='Обработанное')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
                ('processing_status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_set', to='books.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Страница книги',
                'verbose_name_plural': 'Страницы книг',
                'ordering': ['book', 'page_number'],
                'unique_together': {('book', 'page_number')},
            },
        ),
    ]
