# Generated by Django 4.2.7 on 2025-11-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default='', help_text='Буквенный код категории', max_length=20, unique=True, verbose_name='Код'),
        ),
    ]
