# Generated by Django 4.2.7 on 2025-11-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_new_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='binding_details',
            field=models.CharField(blank=True, help_text='Цвет, качество переплета', max_length=200, verbose_name='Детали переплёта'),
        ),
        migrations.AlterField(
            model_name='book',
            name='condition_details',
            field=models.TextField(blank=True, help_text='Изъяны: отсутствие страниц, иллюстраций, загрязнения, изменения цвета, потертости, рассыпанный или "рыхлый" блок и проч.', verbose_name='Детали состояния'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Содержание. Аннотация.', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='ISBN. Если у книги два кода ISBN, указывать надо только первый.', max_length=20, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages_info',
            field=models.CharField(blank=True, help_text='Страниц. Можно указать количество иллюстраций, схем, карт или их наличие.', max_length=200, verbose_name='Страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_place',
            field=models.CharField(blank=True, help_text='Место издания. Город', max_length=200, verbose_name='Место издания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='seller_code',
            field=models.CharField(blank=True, help_text='Когда книг много, они могут храниться на пронумерованных полках или в коробках. Напишите этот номер здесь.', max_length=50, verbose_name='Учетный код продавца'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.TextField(blank=True, help_text='Данные о переводе, принадлежность к серии, редакторов издания, художника-иллюстратора надо указывать здесь. Если произведения, входящие в издание перечислены на титульном листе, их тоже можно здесь указать.', verbose_name='Второе название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Основное название книги.', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_approx',
            field=models.CharField(blank=True, help_text='Если год неизвестен точно, можно указать: 197?, 18??', max_length=10, verbose_name='Год издания (приблизительно)'),
        ),
    ]
