# Generated by Django 4.2.7 on 2025-11-03 11:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_alter_book_binding_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Владелец книги (создатель)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_books', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('none', 'Без статуса'), ('read', 'Прочитано'), ('want_to_read', 'Буду читать'), ('want_to_reread', 'Буду перечитывать')], default='none', help_text='Статус книги', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Полное имя пользователя', max_length=500, verbose_name='ФИО')),
                ('photo', models.ImageField(blank=True, help_text='Фото профиля', null=True, upload_to='users/photos/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, help_text='Описание или биография пользователя', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название библиотеки (например, "Библиотека в Москве")', max_length=200, verbose_name='Название')),
                ('address', models.TextField(help_text='Физический адрес библиотеки', verbose_name='Адрес')),
                ('city', models.CharField(blank=True, help_text='Город', max_length=200, verbose_name='Город')),
                ('country', models.CharField(blank=True, help_text='Страна', max_length=200, verbose_name='Страна')),
                ('description', models.TextField(blank=True, help_text='Описание библиотеки', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(help_text='Владелец библиотеки', on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Библиотека',
                'verbose_name_plural': 'Библиотеки',
                'ordering': ['owner', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название хэштега (например, "#фантастика")', max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(help_text='URL-дружественное имя', max_length=100, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('creator', models.ForeignKey(blank=True, help_text='Пользователь, создавший хэштег (null = общий хэштег)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hashtags', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Хэштег',
                'verbose_name_plural': 'Хэштеги',
                'ordering': ['name'],
                'unique_together': {('name', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='BookHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_hashtags', to='books.book', verbose_name='Книга')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_hashtags', to='books.hashtag', verbose_name='Хэштег')),
            ],
            options={
                'verbose_name': 'Хэштег книги',
                'verbose_name_plural': 'Хэштеги книг',
                'ordering': ['book', 'created_at'],
                'unique_together': {('book', 'hashtag')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='hashtags',
            field=models.ManyToManyField(blank=True, help_text='Хэштеги книги (до 20)', related_name='books', through='books.BookHashtag', to='books.hashtag', verbose_name='Хэштеги'),
        ),
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ForeignKey(blank=True, help_text='Библиотека, в которой находится книга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.library', verbose_name='Библиотека'),
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, help_text='Оценка книги от 1 до 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('review_text', models.TextField(blank=True, help_text='Текст отзыва', verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='Книга')),
                ('user', models.ForeignKey(help_text='Автор отзыва', on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв на книгу',
                'verbose_name_plural': 'Отзывы на книги',
                'ordering': ['-created_at'],
                'unique_together': {('book', 'user')},
            },
        ),
    ]
