# Generated by Django 4.2.7 on 2025-11-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_add_user_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('none', 'Без статуса'), ('reading', 'Читаю'), ('read', 'Прочитано'), ('want_to_read', 'Буду читать'), ('want_to_reread', 'Буду перечитывать')], default='none', help_text='Статус книги', max_length=20, verbose_name='Статус'),
        ),
    ]
