# Generated by Django 4.2.7 on 2025-11-03 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='Родительская категория (если категория является подкатегорией)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='books.category', verbose_name='Родительская категория'),
        ),
    ]
