# Generated by Django 4.2.7 on 2025-11-04 10:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_category_parent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название языка (например, "Русский", "Английский")', max_length=100, unique=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='ISO код языка (например, "ru", "en", "de")', max_length=10, unique=True, verbose_name='Код языка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='circulation',
            field=models.IntegerField(blank=True, help_text='Тираж книги в штуках', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Тираж'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Язык текста книги', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.language', verbose_name='Язык текста'),
        ),
        migrations.CreateModel(
            name='BookReadingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата, когда книга была прочитана', verbose_name='Дата прочтения')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки о прочтении (например, где прочитали, впечатления)', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('book', models.ForeignKey(help_text='Книга, которую прочитали', on_delete=django.db.models.deletion.CASCADE, related_name='reading_dates', to='books.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Дата прочтения',
                'verbose_name_plural': 'Даты прочтения',
                'ordering': ['book', '-date'],
                'unique_together': {('book', 'date')},
            },
        ),
    ]
