# Generated by Django 4.2.7 on 2025-11-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_add_circulation_language_reading_dates'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created_at'], name='books_book_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['library', 'category'], name='books_book_lib_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['owner', 'status'], name='books_book_owner_status_idx'),
        ),
    ]
