# Generated by Django 4.2.7 on 2025-11-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_add_book_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_page',
            field=models.ForeignKey(blank=True, help_text='Страница книги, используемая как обложка (для отображения в списках и карточках)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_books', to='books.bookpage', verbose_name='Обложка'),
        ),
    ]
